spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products_database?createDatabaseIfNotExist=true
    username: root
    password: 6830
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  jackson:
    serialization:
      indent-output: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
